import { emptyReview, applicationsCSV, type Application, type AdmissionsAPI } from './model';
const accepted = { sent: true, method: 'demo-provider', timestamp: '2026-10-03T08:30:00Z' };
const failed = { sent: false, method: 'demo-provider', timestamp: '2026-10-03T08:30:00Z' };
export const demoApplications: Application[] = [
 { reference: 'DEMO-CA-001', name: 'Alex Morgan (example)', email: 'alex@example.com', submittedAt: '2026-10-03T08:30:00Z', answers: { fullName: 'Alex Morgan (example)', email: 'alex@example.com', mobileWhatsapp: 'Demo only', townCity: 'Birmingham', workStatus: 'Employed', rightToWorkUK: 'Yes', highestQualification: 'Degree', pmQualifications: ['No formal PM qualification yet'], ukWorkExperience: 'Yes', englishFirstLanguage: 'Yes', previousExperience: 'Coordinated an internal service improvement project and supported weekly team reporting.', careerObjective: 'Build confidence planning and delivering projects.', currentChallenge: 'Translating practical coordination experience into a structured project approach.', developmentNeeds: ['Project planning', 'Stakeholder engagement'], successMeasure: 'Deliver a clear project plan and explain decisions confidently.', weeklyAvailability: '6 to 8 hours', birminghamAttendance: 'Yes', inPersonProjectAttendance: 'Yes', packageSelection: 'Career Accelerator, with interest in additional executive mentorship', paymentPreference: 'Discuss payment arrangements', confirmationCallDate: '2026-10-06', confirmationCallTime: '14:00', confirmationCallTimeZone: 'Europe/London', confirmationCallAlternative: 'Wednesday afternoon also works.', privacyAcknowledged: true, marketingConsent: false, declaration1: true, declaration2: true, declaration3: true, declaration4: true, declaration5: true, declaration6: true, declaration7: true, cohortDate: '14 November 2026' }, review: emptyReview(), emails: { staff: failed, applicant: failed }, paid: 0, sheetsSynced: false },
 { reference: 'DEMO-CA-002', name: 'Sam Taylor (example)', email: 'sam@example.com', submittedAt: '2026-10-02T11:15:00Z', answers: { fullName: 'Sam Taylor (example)', email: 'sam@example.com', careerObjective: 'Develop practical project leadership skills.', packageSelection: 'Career Accelerator', paymentPreference: 'Two instalments', confirmationCallDate: '2026-10-07', confirmationCallTime: '10:30', confirmationCallTimeZone: 'Europe/London', privacyAcknowledged: true }, review: { ...emptyReview(), version: 1, status: 'Call arranged', callDate: '2026-10-07', callTime: '10:30', callZone: 'Europe/London', notes: 'Demo: appointment agreed with applicant. Discuss availability and learning objectives.', updatedAt: '2026-10-03T09:00:00Z', updatedBy: 'Preview user' }, emails: { staff: accepted, applicant: accepted }, paid: 0, sheetsSynced: false },
 { reference: 'DEMO-CA-003', name: 'Jordan Lee (example)', email: 'jordan@example.com', submittedAt: '2026-10-01T16:05:00Z', answers: { fullName: 'Jordan Lee (example)', email: 'jordan@example.com', careerObjective: 'Strengthen project delivery skills.', packageSelection: 'Career Accelerator', paymentPreference: 'Discuss employer sponsorship', confirmationCallDate: '2026-10-02', confirmationCallTime: '15:00', confirmationCallTimeZone: 'Europe/London', privacyAcknowledged: true }, review: { ...emptyReview(), version: 2, status: 'Accepted', callDate: '2026-10-02', callTime: '15:00', callZone: 'Europe/London', notes: 'Demo: call completed. Acceptance and sponsorship arrangements to be communicated separately.', updatedAt: '2026-10-03T09:20:00Z', updatedBy: 'Preview user' }, emails: { staff: accepted, applicant: accepted }, paid: 0, sheetsSynced: false }
];
export function createDemoAPI(): AdmissionsAPI {
 let applications: Application[] = structuredClone(demoApplications); let user: string | null = 'Preview user';
 return {
 session: async () => ({ user }), login: async () => { user = 'Preview user'; return { user }; }, logout: async () => { user = null; }, list: async () => structuredClone(applications),
 save: async (reference, review) => {
  const a = applications.find(a => a.reference === reference)!;
  if (a.review.version !== review.version) throw new Error('Refresh before saving.');
  if (review.status === 'Call arranged' && !(review.callDate && review.callTime && review.callZone.trim())) throw new Error('An arranged call needs a date, time and time zone.');
  if ((review.callDate || review.callTime || review.callZone) && !(review.callDate && review.callTime && review.callZone.trim())) throw new Error('Enter a date, time and time zone together.');
  a.review = { ...review, version: review.version + 1, updatedAt: new Date().toISOString(), updatedBy: 'Preview user' }; return structuredClone(a.review);
 },
 resend: async (reference, kind) => { const a = applications.find(a => a.reference === reference)!; if (kind === 'applicant' && ['Accepted', 'Not accepted'].includes(a.review.status)) throw new Error('A decision email must be sent separately.'); a.emails[kind] = { ...accepted, timestamp: new Date().toISOString() }; return { sent: true }; },
 export: async () => new Blob([applicationsCSV(applications)], { type: 'text/csv;charset=utf-8' })
 };
}
