import { CareerEnquiriesRegister } from './CareerEnquiriesRegister';
import React, { useEffect, useState } from 'react';
import { admissionsAPI } from '../admissions/api';
import { answerLabels, displayAnswer, reviewStatuses, type AdmissionsAPI, type Application, type Review, type EmailState } from '../admissions/model';
import '../admissions/dashboard.css';
import { Logo } from './Logo';
const date = (value: string) => value ? new Date(value).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' }) : 'Not recorded';
const emailText = (value: EmailState) => !value ? 'No send recorded' : value.sent ? 'Accepted by email provider' : 'Not sent / needs attention';
export function AdmissionsDashboard({ api = admissionsAPI, demo = false, initial = [] }: { api?: AdmissionsAPI; demo?: boolean; initial?: Application[] }) {
 const [user, setUser] = useState<string | null>(demo ? 'Preview user' : null);
 const [loading, setLoading] = useState(!demo);
 const [applications, setApplications] = useState(initial);
 const [selected, setSelected] = useState<string | null>(null);
 const [query, setQuery] = useState(''); const [filter, setFilter] = useState('All applications');
 const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
 const [email, setEmail] = useState(''); const [password, setPassword] = useState('');
 const [draft, setDraft] = useState<Review | null>(null);
 const application = applications.find(a => a.reference === selected);
 const fail = (e: any) => { setError(e.message || 'Something went wrong. Please try again.'); if (e.status === 401) { setUser(null); setApplications([]); setSelected(null); setDraft(null); } };
 useEffect(() => { let active = true; (async () => { try { const session = await api.session(); if (!active) return; setUser(session.user); if (session.user) { const records = await api.list(); if (active) setApplications(records); } } catch(e) { if (active) fail(e); } finally { if(active) setLoading(false); } })(); return () => { active = false; }; }, [api]);
 const open = (a: Application) => { setSelected(a.reference); setDraft({ ...a.review }); setError(''); setMessage(''); };
 const dirty = application && draft && JSON.stringify(draft) !== JSON.stringify(application.review);
 useEffect(() => { if (!dirty) return; const warn = (event: BeforeUnloadEvent) => { event.preventDefault(); event.returnValue = ''; }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn); }, [dirty]);
 const leave = () => !dirty || window.confirm('Discard your unsaved review changes?');
 async function refresh() { if (!leave()) return; setBusy(true); setError(''); try { const records = await api.list(); setApplications(records); const item = records.find(a => a.reference === selected); setDraft(item ? { ...item.review } : null); setMessage('Applications refreshed.'); } catch(e) { fail(e); } finally { setBusy(false); } }
 async function signIn(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { const session = await api.login(email, password); setPassword(''); setUser(session.user); setApplications(await api.list()); } catch(e) { fail(e); } finally { setBusy(false); } }
 async function signOut() { if (!leave()) return; setBusy(true); try { await api.logout(); setUser(null); setApplications([]); setDraft(null); setSelected(null); setMessage('Signed out.'); } catch(e) { fail(e); } finally { setBusy(false); } }
 async function save(e: React.FormEvent) { e.preventDefault(); if (!application || !draft) return; setBusy(true); setError(''); setMessage(''); try { const review = await api.save(application.reference, draft); setApplications(items => items.map(a => a.reference === application.reference ? { ...a, review } : a)); setDraft(review); setMessage('Review saved. No email or payment request has been sent.'); } catch(e) { fail(e); } finally { setBusy(false); } }
 async function resend(kind: 'staff' | 'applicant') {
  if (!application || !window.confirm(kind === 'staff' ? 'Send this application to the configured admissions inbox? This may duplicate an earlier email.' : 'Send the application acknowledgement again? It says the application is awaiting review, with payment requested only after acceptance. This may duplicate an earlier email.')) return;
  setBusy(true); setError(''); setMessage('');
  try { const result = await api.resend(application.reference, kind); setApplications(await api.list()); setMessage(result.sent ? (demo ? 'Demo only: email action simulated. No email was sent.' : 'The email provider accepted the email. Check the recipient inbox or Resend delivery log to confirm delivery.') : 'The email was not sent. Ask Mugo to check the email configuration and Resend logs. The application is still saved.'); } catch(e) { fail(e); } finally { setBusy(false); }
 }
 async function download() { setBusy(true); setError(''); try { const blob = await api.export(); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = demo ? 'WBD-demo-applications.csv' : 'WBD-applications.csv'; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); setMessage('Spreadsheet export downloaded. Store applicant information securely.'); } catch(e) { fail(e); } finally { setBusy(false); } }
 const filtered = applications.filter(a => (filter === 'All applications' || (filter === 'Email needs attention' ? !a.emails.staff?.sent || !a.emails.applicant?.sent : a.review.status === filter)) && [a.name, a.email, a.reference].join(' ').toLowerCase().includes(query.toLowerCase()));
 return <div className="admissions">
  {demo && <div className="ad-demo">REVIEW PREVIEW ONLY <span>Fictional applications. No real emails, payments or website changes.</span></div>}
  <header className="ad-header"><div><a href={demo ? '#' : '/'} aria-label="WOW Business and Digital home" className="ad-wordmark"><Logo lightMode size="lg" /></a><span className="ad-private">Private admissions</span></div>{user && <button className="ad-quiet" onClick={signOut} disabled={busy}>Sign out</button>}</header>
  <main className="ad-main">
   <div className="ad-heading"><div><p className="ad-eyebrow">Career Accelerator</p><h1>Applications</h1><p>One place to review, arrange a call and record the next step.</p></div>{user && <div className="ad-actions"><button onClick={refresh} disabled={busy}>Refresh</button><button onClick={download} disabled={busy}>Export spreadsheet</button></div>}</div>
   {error && <div role="alert" className="ad-alert">{error}</div>}{message && <div role="status" className="ad-message">{message}</div>}
   {loading ? <p role="status">Checking staff access...</p> : !user ? <section className="ad-login ad-card"><p className="ad-eyebrow">Authorised staff only</p><h2>Sign in to admissions</h2><p>Use the staff access details supplied by your website administrator.</p><form onSubmit={signIn}><label>Email address<input type="email" autoComplete="username" value={email} onChange={e => setEmail(e.target.value)} required /></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} required /></label><button className="ad-primary" disabled={busy}>{busy ? 'Signing in...' : 'Sign in'}</button></form><p className="ad-small">Lost access? Ask Mugo to reset your staff password. Applicant information is not available without sign-in.</p>{demo && <button onClick={async () => { setUser('Preview user'); setApplications(await api.list()); }}>Return to demo</button>}</section> : <>
    {!application ? <>
     {!demo && <CareerEnquiriesRegister />}
     <div className="ad-stats"><div><strong>{applications.length}</strong><span>Applications received</span></div><div><strong>{applications.filter(a => a.review.status === 'Received').length}</strong><span>Awaiting review</span></div><div><strong>{applications.filter(a => a.review.status === 'Call arranged').length}</strong><span>Calls arranged</span></div><div><strong>{applications.filter(a => !a.emails.applicant?.sent || !a.emails.staff?.sent).length}</strong><span>Emails to check</span></div></div>
     <section className="ad-card"><div className="ad-toolbar"><label>Find an application<input type="search" placeholder="Search name, email or reference" value={query} onChange={e => setQuery(e.target.value)} /></label><label>Show<select value={filter} onChange={e => setFilter(e.target.value)}>{['All applications', ...reviewStatuses, 'Email needs attention'].map(s => <option key={s}>{s}</option>)}</select></label></div><div className="ad-table-wrap"><table><thead><tr><th>Applicant</th><th>Received</th><th>Review status</th><th>Applicant email</th><th><span className="ad-sr">Action</span></th></tr></thead><tbody>{filtered.map(a => <tr key={a.reference}><td><strong>{a.name}</strong><span>{a.reference}</span></td><td>{date(a.submittedAt)}</td><td><span className={'ad-pill ' + (a.review.status === 'Accepted' ? 'ad-good' : '')}>{a.review.status}</span></td><td><span className={a.emails.applicant?.sent ? '' : 'ad-warn'}>{emailText(a.emails.applicant)}</span></td><td><button aria-label={'Open application for ' + a.name} onClick={() => open(a)}>Open application</button></td></tr>)}</tbody></table></div>{!filtered.length && <p className="ad-empty">{applications.length ? 'No applications match your search.' : 'No applications are available in this server register. Ask Mugo to confirm this deployment uses the original saved data folder.'}</p>}</section>
     <div className="ad-guidance"><h2>A clear application journey</h2><p>Application received. Arrange the 10-minute confirmation call. Record the outcome. Once accepted, email the applicant their agreed payment schedule and instructions.</p><p>Changing a status here does not send a decision email or request payment.</p></div>
    </> : <>
     <button className="ad-back" onClick={() => { if (leave()) { setSelected(null); setDraft(null); setMessage(''); } }}>Back to all applications</button>
     <div className="ad-record-title"><div><p className="ad-eyebrow">{application.reference}</p><h2>{application.name}</h2><p>{application.email} <span className="ad-divider">|</span> Received {date(application.submittedAt)}</p></div><span className="ad-pill">{application.review.status}</span></div>
     <div className="ad-columns"><div>
      <section className="ad-card"><h3>Application answers</h3><p className="ad-small">Original answers as submitted. Internal review notes are kept separately.</p><dl className="ad-answers">{Object.entries(answerLabels).filter(([key]) => application.answers[key] !== undefined && displayAnswer(application.answers[key]) !== '').map(([key, label]) => <div key={key}><dt>{label}</dt><dd>{displayAnswer(application.answers[key])}</dd></div>)}</dl></section>
     </div><aside>
      <section className="ad-card"><h3>Review and confirmation call</h3><div className="ad-call"><strong>Applicant's requested slot</strong><p>{String(application.answers.confirmationCallDate || 'Date to agree')} at {String(application.answers.confirmationCallTime || 'time to agree')}<br />{String(application.answers.confirmationCallTimeZone || 'Time zone to agree')}</p><p className="ad-small">A preference, not a confirmed booking. Agree the appointment with the applicant before recording it below.</p></div>
       {draft && <form onSubmit={save}><label>Review status<select value={draft.status} onChange={e => setDraft({ ...draft, status: e.target.value as Review['status'] })}>{reviewStatuses.map(s => <option key={s}>{s}</option>)}</select></label><div className="ad-form-row"><label>Confirmed call date<input type="date" value={draft.callDate} onChange={e => setDraft({ ...draft, callDate: e.target.value })} /></label><label>Confirmed time<input type="time" value={draft.callTime} onChange={e => setDraft({ ...draft, callTime: e.target.value })} /></label></div><label>Confirmed time zone<input placeholder="e.g. Europe/London" value={draft.callZone} maxLength={100} onChange={e => setDraft({ ...draft, callZone: e.target.value })} /></label><label>Internal notes<textarea rows={4} maxLength={10000} placeholder="Call outcome, next step and any agreed arrangements" value={draft.notes} onChange={e => setDraft({ ...draft, notes: e.target.value })} /></label><button className="ad-primary" disabled={busy || !dirty}>{busy ? 'Working...' : 'Save review'}</button><p className="ad-small">This saves an internal record only. Contact the applicant separately to confirm the call or communicate a decision. Payment is requested only after acceptance.</p>{application.review.updatedAt && <p className="ad-small">Last saved by {application.review.updatedBy} on {date(application.review.updatedAt)}.</p>}</form>}
      </section>
      <section className="ad-card"><h3>Email checks</h3><p className="ad-small">Provider acceptance is not proof of inbox delivery. Check Resend delivery logs and the recipient's spam folder if an email is missing.</p>{(['applicant', 'staff'] as const).map(kind => <div className="ad-email" key={kind}><strong>{kind === 'staff' ? 'Admissions inbox alert' : 'Applicant acknowledgement'}</strong><p>{emailText(application.emails[kind])}</p>{application.emails[kind]?.timestamp && <p className="ad-small">Last attempt: {date(application.emails[kind]!.timestamp)} via {application.emails[kind]!.method}</p>}<button disabled={busy || (kind === 'applicant' && ['Accepted', 'Not accepted'].includes(application.review.status))} onClick={() => resend(kind)}>{kind === 'staff' ? 'Send application to admissions' : 'Resend acknowledgement'}</button></div>)}<p className="ad-small">The acknowledgement confirms receipt, not acceptance. After a decision, send the relevant decision email manually.</p></section>
      <section className="ad-card"><h3>Payments recorded</h3><strong className="ad-money">{new Intl.NumberFormat('en-GB', { style: 'currency', currency: 'GBP' }).format(application.paid / 100)}</strong><p className="ad-small">Verified live Stripe payments, less recorded refunds. Test payments are excluded. Bank transfers and payments without this application reference may not appear.</p></section>
     </aside></div>
    </>}
   </>}
  </main><footer className="ad-footer">WOW Business &amp; Digital Ltd <span>Staff access only. {demo ? 'Preview changes reset when this file is reopened.' : 'Sign out when you finish.'}</span></footer>
 </div>;
}
