import React, { useState } from 'react';
import { sessions, sessionOpen } from '../engagement/options';
import './career-explore.css';
export function CareerExplore({ corporate = false }: { corporate?: boolean }) {
 const [kind, setKind] = useState(corporate ? 'corporate' : 'taster'); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [result, setResult] = useState<any>(null);
 async function submit(e: React.FormEvent<HTMLFormElement>) {
  e.preventDefault(); const form = e.currentTarget; const data = new FormData(form); setBusy(true); setError('');
  try { const body = Object.fromEntries(['name','email','phone','company','employees','message','session','website'].map(k => [k, String(data.get(k) || '')])); const response = await fetch('/api/career-enquiries', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...body, kind, consent: data.get('consent') === 'on' }) }); const answer = await response.json(); if (!response.ok) throw new Error(answer.error || 'Please try again.'); setResult(answer); form.reset(); } catch(e: any) { setError(e.message || 'The result could not be confirmed. Contact WOW before submitting again.'); } finally { setBusy(false); }
 }
 return <main className="career-explore"><div className="ce-wrap"><a href="?page=pm-career-accelerator">Career Accelerator</a><p className="ce-eyebrow">{corporate ? 'Develop your people' : 'Free taster and adviser calls'}</p><h1>{corporate ? 'Support your people. Build their capability.' : 'Try it out. Talk it through.'}</h1><p className="ce-lead">{corporate ? 'Sponsor employees or discuss support tailored to your organisation. Attractive corporate packages and flexible arrangements are available.' : 'Explore practical project management and the interpersonal skills that help you put your qualifications to work.'}</p>
 {!corporate && <div className="ce-cards"><section><h2>Free simulated project taster</h2><p>Saturday 10 or Friday 16 October 2026, 10am to 2pm UK time.</p><p>Work through a simulated project and explore planning, teamwork, stakeholder expectations, difficult conversations and presenting your ideas with confidence.</p></section><section><h2>A free 15-minute adviser call</h2><p>Thursday 8 or Friday 9 October 2026, between 11am and 2pm UK time.</p><p>Discuss your goals, ask questions and see whether the programme fits. Choose a predefined time below. This is separate from the application confirmation call.</p></section></div>}
 <div className="ce-notice"><strong>November cohort starts 14 November 2026. Places are limited.</strong><p>No payment is taken when you apply. Payment is requested only after acceptance, according to your agreed schedule.</p><a className="ce-button" href="?page=pm-registration">Apply for the November cohort</a><p>You can apply now and still attend a taster or adviser call. A taster or call does not reserve a programme place.</p></div>
 <section className="ce-form"><h2>{corporate ? 'Discuss a corporate package' : 'Request your session'}</h2>{!corporate && <p>Requests are reviewed by WOW. Your session is only confirmed when you receive a separate confirmation email with joining details. Calendar booking is not yet connected.</p>}
 {result ? <div role="status"><h3>Request received</h3><p>{result.message}</p><p className="ce-reference">Reference: {result.reference}</p><p>{result.emailAccepted ? 'An acknowledgement has been accepted by our email provider. Check your inbox and spam folder.' : 'The acknowledgement email could not be sent. Please keep this reference and contact WOW if you need help.'}</p></div> : <form onSubmit={submit}>
 {!corporate && <><label>What would you like?<select value={kind} onChange={e => setKind(e.target.value)}><option value="taster">Free taster session</option><option value="call">15-minute adviser call</option></select></label><label>Preferred session (UK time)<select name="session" key={kind} required defaultValue=""><option value="" disabled>Select a session</option>{sessions.filter(s => s.kind === kind && sessionOpen(s)).map(s => <option key={s.id} value={s.id}>{s.label}</option>)}</select></label></>}
 {corporate && <label>Company name<input name="company" maxLength={254} required autoComplete="organization" /></label>}
 <label>{corporate ? 'Contact name' : 'Full name'}<input name="name" required maxLength={254} autoComplete="name" /></label><label>{corporate ? 'Work email' : 'Email address'}<input name="email" type="email" required maxLength={254} autoComplete="email" /></label>
 {corporate && <><label>Contact phone number<input name="phone" type="tel" required maxLength={254} autoComplete="tel" /></label><label>Number of employees (optional)<input name="employees" maxLength={254} /></label></>}
 <label>{corporate ? 'What support are you looking for? (optional)' : 'Questions or access requirements (optional)'}<textarea name="message" maxLength={2000} rows={4} /></label><div hidden><label>Leave blank<input name="website" tabIndex={-1} autoComplete="off" /></label></div><label className="ce-check"><input type="checkbox" name="consent" required /><span>I have read the <a href="?page=privacy" target="_blank" rel="noreferrer">privacy notice</a> and agree to WOW contacting me about this request.</span></label>{error && <p role="alert">{error}</p>}<button className="ce-button" disabled={busy}>{busy ? 'Sending...' : corporate ? 'Send corporate enquiry' : 'Send session request'}</button><p>No payment is taken. This form does not submit a Career Accelerator application.</p></form>}
 </section><p><a href={corporate ? '?page=career-explore' : '?page=corporate-career'}>{corporate ? 'Explore a free taster or adviser call' : 'Employer sponsorship and corporate packages'}</a></p></div></main>;
}
