import React from 'react';
import { CAREER_ACCELERATOR as p } from '../data/careerAccelerator';

export const ProgrammePolicies = ({ privacy }: { privacy: boolean }) => <section className="max-w-4xl mx-auto px-5 py-12 space-y-5 text-slate-800">
  <h1 className="text-3xl font-bold">{privacy ? 'Privacy notice' : 'Career Accelerator information and application terms'}</h1>
  <p>WOW Business and Digital Ltd · Updated 2 October 2026</p>
  {privacy ? <>
    <h2 className="text-xl font-bold">Who handles your information</h2><p>WOW Business and Digital Ltd is responsible for information submitted through this website. Contact <a className="underline" href={`mailto:${p.email}`}>{p.email}</a> about your information or this notice.</p>
    <h2 className="text-xl font-bold">Information and purpose</h2><p>Stripe processes card payments; WOW stores the payment reference, amount, status and date, not your card details. Test payments do not reserve a place. We collect the contact details and answers you provide in an enquiry or programme application. We use them to respond, review your application, arrange agreed services, manage participation and payments, and keep appropriate records. Please do not send identity documents, card details or unnecessary health or financial information through these forms.</p>
    <p>We process application and service information to take steps at your request before an agreement and to deliver agreed services. Optional marketing uses your consent, which you can withdraw by contacting us. Declining marketing does not affect your application.</p>
    <h2 className="text-xl font-bold">Storage and access</h2><p>Submitted records are stored on our website server and may be sent to our business inbox and admissions tracking sheet. Authorised WOW staff and delivery personnel access information needed for their role. Hosting, email and business collaboration providers process it on our behalf. We do not sell applicant information.</p>
    <p>The Career Accelerator form holds unsent answers in the current page only. It does not save new application drafts in persistent browser storage. Old registration drafts are removed after a successful submission. If a save fails, your answers remain available in the page for retry.</p>
    <h2 className="text-xl font-bold">Workspace access</h2><p>We record your name, email and reason for requesting simulation access. WOW reviews requests and grants or withdraws individual access. Sign-in codes expire after 24 hours and work once. An essential secure session cookie keeps approved participants signed in for up to eight hours. We store hashed sign-in credentials and session tokens, rather than the original codes. You can sign out to end the session.</p>
    <h2 className="text-xl font-bold">Browser storage</h2><p>The project simulation demonstration can save notes, tasks and progress in this browser. It uses fictional scenario information and does not sync that work to a shared team account. You can download your notes and clear the demonstration using its reset control. Do not enter confidential or personal information into the demonstration. No advertising or analytics cookies have been added in this review build.</p>
    <h2 className="text-xl font-bold">Retention and your choices</h2><p>We retain information while handling your enquiry or application and, if you join, while administering the programme and its records. We review records and remove information that is no longer needed, subject to accounting, dispute and other applicable record requirements. Contact us for the retention period applying to your record.</p>
    <p>You can ask about access, correction, deletion, restriction, objection or transfer of your information, subject to applicable rights. You may also complain to the Information Commissioner’s Office at ico.org.uk. Contact WOW first if you would like us to address a concern.</p>
  </> : <>
    <h2 className="text-xl font-bold">Offer and application</h2><p>The {p.title} begins on {p.startDate} and runs for six months. Submission records an application for review. A verified live payment of at least £50 reserves a place subject to that review; submitting the form alone does not reserve a place. WOW confirms enrolment and delivery arrangements separately. Sponsorship must be agreed in writing.</p>
    <h2 className="text-xl font-bold">Learning and work</h2><p>{p.workDescription} Three-hour and five-day simulated project exercises are additional learning activities and are labelled as simulations. We do not guarantee employment, earnings or a third-party client reference.</p>
    <p>Delivery combines virtual sessions, supervised project work and coaching. Any workshop or in-person project expectations and remote alternatives are confirmed before you accept a place. Certificates describe participation or completion under the stated criteria; no external accreditation is implied.</p>
    <h2 className="text-xl font-bold">Fees and executive mentorship</h2><p>The standard fee is £1,000, or £900 paid in full by {p.earlyDeadline}. The standard instalment plan is £500 by {p.earlyDeadline} and £500 by {p.instalmentDeadline}. The executive mentorship package is £1,250: {p.mentorshipScope} Previous payments are credited against the total. The early settlement offer applies to the standard package.</p>
    <p>A £50 registration deposit reserves a place subject to application review. It is credited against the total tuition, including the first instalment where applicable. The deposit reduces the £900 early settlement balance to £850, or the first £500 instalment to £450. Final payment is due by {p.finalDeadline} unless an employer sponsorship arrangement has been agreed in writing. WOW is not VAT registered.</p>
    <h2 className="text-xl font-bold">Cancellation and changes</h2><p>The stated deposit policy is non-refundable after acceptance and reservation, subject to your statutory rights and applicable cancellation rules. This does not remove any right to cancel or refund that applies by law. Please read these terms before payment and contact WOW if you need further information. Please email {p.email} with your reference to request cancellation or discuss a change.</p>
    <p>If WOW cannot deliver the confirmed programme, we will contact you about an alternative or repayment for services not supplied. Material changes to dates, scope or fees will be explained before you agree to them.</p>
    <h2 className="text-xl font-bold">Contact and concerns</h2><p>For an application update, accessibility discussion or complaint, email {p.email} with your reference. Please keep the programme and invoice confirmation for your records.</p>
  </>}
</section>;
