import { PaymentsSection } from '../src/components/PaymentsSection';
import React from 'react';
import assert from 'node:assert/strict';
import { renderToStaticMarkup } from 'react-dom/server';
import { Version2Section } from '../src/components/Version2Section';
import { AboutSection } from '../src/components/AboutSection';
import { ContactSection } from '../src/components/ContactSection';
import { Footer } from '../src/components/Footer';
import { Header } from '../src/components/Header';
import { ServicesSection } from '../src/components/ServicesSection';
import { TrainingRegistrationForm } from '../src/components/TrainingRegistrationForm';
import { ProjectManagementRegistrationPage, initialApplication } from '../src/components/ProjectManagementRegistrationPage';
import { ProjectManagementCareerAcceleratorSection } from '../src/components/ProjectManagementCareerAcceleratorSection';
const noOp=()=>{};
const render=(node:React.ReactNode)=>renderToStaticMarkup(node);
const home=render(<Version2Section setActiveTab={noOp}/>);
assert(home.indexOf('<svg') < home.indexOf('<h1'));
for(const text of ['For individuals','For small businesses','For larger organisations','Five connected ways','One lead. The right people for your project.']) assert(home.includes(text),text);
const about=render(<AboutSection setActiveTab={noOp}/>);
for(const text of ['From evidence to practical results','Understand','Deliver','Improve','smaller practical projects','Her work has included']) assert(about.includes(text),text);
assert(!about.includes('Zimbabwe'));
const contact=render(<ContactSection/>);
assert.equal((contact.match(/<form/g)||[]).length,1);
assert(contact.includes('value="other"') && contact.includes('Phone (optional)') && contact.includes('Organisation (optional)'));
assert(!contact.includes('Routing Queue'));
const footer=render(<Footer setActiveTab={noOp}/>);
for(const text of ['Become an associate','Fees and payments','Privacy notice','Programme terms'])assert(footer.includes(text),text);
for(const text of ['WOW AI Suite','Zimbabwe','personality'])assert(!footer.includes(text),text);
const header=render(<Header activeTab="home" setActiveTab={noOp}/>);
assert(header.indexOf('About &amp; Experience')<header.indexOf('>Services<'));
assert(!header.includes('Payments'));
const services=render(<ServicesSection activeTab="services" setActiveTab={noOp}/>);
for(const text of ['Programme and Project Delivery','Digital Transformation','Change and Adoption','PMO and Governance'])assert(services.includes(text),text);
const support=render(<ServicesSection activeTab="career-coaching" setActiveTab={noOp}/>);
assert(support.includes('Career coaching and CV support'));
const initial=initialApplication();
assert(Object.values(initial).every(v => Array.isArray(v)?v.length===0:v===false||v===''));
const form=render(<TrainingRegistrationForm formData={initial} setFormData={noOp} onSubmit={noOp}/>);
assert(form.includes('Submit application')&&!form.includes('Submit and Pay'));
assert(!form.includes('checked=""'));
assert(form.indexOf('Preferred start time') > form.indexOf('1. Personal Details'));
assert(form.indexOf('Preferred start time') < form.indexOf('Submit application'));
assert(form.includes('confirmation call is part of the application process'));
assert(form.includes('confirmation-call-date') && form.includes('confirmation-call-time') && form.includes('confirmation-call-zone'));
const mentorship=render(<TrainingRegistrationForm formData={{...initial,packageSelection:'Career Accelerator with optional executive mentorship add-on'}} setFormData={noOp} onSubmit={noOp}/>);
assert(mentorship.includes('Discuss payment arrangements for the executive mentorship add-on'));
assert(!mentorship.includes('value="Pay in full £900'));
const application=render(<ProjectManagementRegistrationPage setActiveTab={noOp}/>);
assert(application.includes('14 November 2026')&&application.includes('No payment is required at this stage'));
const programme=render(<ProjectManagementCareerAcceleratorSection setActiveTab={noOp}/>);
for(const text of ['14 November 2026','three private 60-minute sessions','Practise a project with WOW','Request simulation workspace access'])assert(programme.includes(text),text);
assert(programme.indexOf('<h1')<programme.indexOf('Optional executive mentorship add-on'));
console.log('PASS restored homepage, About process, one contact form, compact footer, navigation, four service names, blank application, mentorship pricing and workspace route');

const payments=render(<PaymentsSection setActiveTab={noOp}/>);
assert(payments.includes('Pay £50.00 with Stripe'));
assert(payments.includes('Email my payment link'));
assert(!payments.includes('New applicants: apply'));
assert(payments.includes('Do not submit another application'));
assert(payments.includes('type="submit"'));
console.log('PASS public Payments entry: visible Stripe action, link recovery, no application detour');
